# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d56a7c4a2c3ec3fed793f9063e33ed67a10d821fb555a637c5ddff1c9fbad095ff4997e0661127a637e39a5afba420712c9fc61827df24893ac3d5a74a53d70c

test:
  secret_key_base: 8b5ee4d70081aa88221f9f837cb7a49ee032b2cf3fa942c5a9b430b57acd18c0bf73cbdee1aeb454d904b51375b35c3c5717bbb11553a384652489096abf8b0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
